version: '3.8'

services:

  directus:
    image: directus/directus:10.8.3
    container_name: directus
    restart: unless-stopped
    ports:
      - "8200:8055"
    volumes:
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

  database:
    image: postgis/postgis:14-master
    container_name: database
    restart: unless-stopped
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus

networks:
  directus:

